# This is a basic workflow to help you get started with Actions

name: Backup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs every day at midnight
  schedule:
    - cron: '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "backup"
  backup:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'

      - run: yarn
      - run: yarn dump

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update shaders
